[package]
name = "reth-downloaders"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Implementations of various block downloaders"

[dependencies]
# reth
reth-interfaces.workspace = true
reth-primitives.workspace = true
reth-tasks.workspace = true
reth-provider.workspace = true

# async
futures.workspace = true
futures-util.workspace = true
pin-project.workspace = true
tokio = { workspace = true, features = ["sync"] }
tokio-stream.workspace = true
tokio-util = { workspace = true, features = ["codec"] }

# metrics
reth-metrics.workspace = true
metrics.workspace = true

# misc
tracing.workspace = true
rayon.workspace = true
thiserror.workspace = true

# optional deps for the test-utils feature
reth-db = { workspace = true, optional = true }
alloy-rlp = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }
itertools = { workspace = true, optional = true }

[dev-dependencies]
reth-db = { workspace = true, features = ["test-utils"] }
reth-interfaces = { workspace = true, features = ["test-utils"] }
reth-tracing.workspace = true

assert_matches.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
alloy-rlp.workspace = true
itertools.workspace = true

tempfile.workspace = true

[features]
test-utils = ["dep:alloy-rlp", "dep:tempfile", "dep:itertools", "reth-db/test-utils", "reth-interfaces/test-utils"]
