[package]
name = "reth-dns-discovery"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Support for EIP-1459 Node Discovery via DNS"

[dependencies]
# reth
reth-primitives.workspace = true
reth-net-common.workspace = true

# ethereum
alloy-rlp.workspace = true
secp256k1 = { workspace = true, features = ["global-context", "rand-std", "recovery", "serde"] }
enr = { workspace = true, default-features = false, features = ["rust-secp256k1"] }

# async/futures
tokio = { workspace = true, features = ["io-util", "net", "time"] }
tokio-stream.workspace = true

# trust-dns
trust-dns-resolver = "0.23"

# misc
data-encoding = "2"
async-trait.workspace = true
linked_hash_set = "0.1"
schnellru.workspace = true
thiserror.workspace = true
tracing.workspace = true
parking_lot.workspace = true
serde = { workspace = true, optional = true }
serde_with = { version = "3.3.0", optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["sync", "rt", "rt-multi-thread"] }
reth-tracing.workspace = true

[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_with"]
