[package]
name = "reth-stages"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Staged syncing primitives used in reth."

[package.metadata.cargo-udeps.ignore]
normal = [
    # Used for diagrams in docs
    "aquamarine",
]

[dependencies]
# reth
reth-primitives.workspace = true
reth-interfaces.workspace = true
reth-db.workspace = true
reth-codecs = { path = "../storage/codecs" }
reth-provider.workspace = true
reth-trie = { path = "../trie" }
reth-tokio-util.workspace = true

# revm
revm.workspace = true

# async
tokio = { workspace = true, features = ["sync"] }
tokio-stream.workspace = true
async-trait.workspace = true
futures-util.workspace = true
pin-project.workspace = true

# observability
tracing.workspace = true

# io
serde.workspace = true

# metrics
reth-metrics.workspace = true
metrics.workspace = true

# misc
thiserror.workspace = true
aquamarine.workspace = true
itertools.workspace = true
rayon.workspace = true
num-traits = "0.2.15"

[dev-dependencies]
# reth
reth-primitives = { workspace = true, features = ["test-utils", "arbitrary"] }
reth-db = { workspace = true, features = ["test-utils", "mdbx"] }
reth-interfaces = { workspace = true, features = ["test-utils"] }
reth-downloaders = { path = "../net/downloaders" }
reth-eth-wire = { path = "../net/eth-wire" } # TODO(onbjerg): We only need this for [BlockBody]
reth-blockchain-tree = { path = "../blockchain-tree" }
reth-revm = { path = "../revm" }
reth-trie = { path = "../trie", features = ["test-utils"] }

alloy-rlp.workspace = true
itertools.workspace = true
tokio = { workspace = true, features = ["rt", "sync", "macros"] }
assert_matches.workspace = true
rand.workspace = true
paste = "1.0"

# Stage benchmarks
pprof = { version = "0.12", features = ["flamegraph", "frame-pointer", "criterion"] }
criterion = { version = "0.5", features = ["async_futures"] }

# io
serde_json.workspace = true

[features]
test-utils = ["reth-interfaces/test-utils"]

[[bench]]
name = "criterion"
harness = false
required-features = ["test-utils"]
