[package]
name = "reth-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# reth
reth-network.workspace = true
reth-net-nat.workspace = true
reth-discv4.workspace = true
reth-downloaders.workspace = true
reth-primitives.workspace = true

# io
serde.workspace = true
serde_json.workspace = true

# crypto
secp256k1 = { workspace = true, features = ["global-context", "rand-std", "recovery"] }

# misc
tempfile.workspace = true

[dev-dependencies]
confy.workspace = true
toml.workspace = true
