[package]
name = "reth-libmdbx"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0"
description = "Idiomatic and safe MDBX wrapper with good licence"
homepage.workspace = true
repository.workspace = true

[lib]
name = "reth_libmdbx"

[dependencies]
bitflags.workspace = true
byteorder = "1"
derive_more = "0.99"
indexmap = "2"
libc = "0.2"
parking_lot.workspace = true
thiserror.workspace = true

ffi = { package = "reth-mdbx-sys", path = "./mdbx-sys" }

[features]
default = []
return-borrowed = []

[dev-dependencies]
pprof = { workspace = true, features = ["flamegraph", "frame-pointer", "criterion"] }
criterion.workspace = true
rand.workspace = true
rand_xorshift = "0.3"
tempfile.workspace = true

[[bench]]
name = "cursor"
harness = false

[[bench]]
name = "transaction"
harness = false
