[package]
name = "reth-interfaces"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
reth-codecs.workspace = true
reth-nippy-jar.workspace = true
reth-primitives.workspace = true
reth-rpc-types.workspace = true
reth-network-api.workspace = true
# TODO(onbjerg): We only need this for [BlockBody]
reth-eth-wire.workspace = true

# eth
revm-primitives.workspace = true

# async
async-trait.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["sync"] }
tokio-stream.workspace = true

# misc
auto_impl = "1.0"
thiserror.workspace = true
tracing.workspace = true
rand.workspace = true
arbitrary = { workspace = true, features = ["derive"], optional = true }
secp256k1 = { workspace = true, default-features = false, features = [
    "alloc",
    "recovery",
    "rand",
], optional = true }
modular-bitfield = "0.11.2"
parking_lot.workspace = true
clap = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
reth-db = { workspace = true, features = ["test-utils"] }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true, features = ["sync"] }
arbitrary = { workspace = true, features = ["derive"] }
secp256k1 = { workspace = true, features = ["alloc", "recovery", "rand"] }

[features]
test-utils = ["tokio-stream/sync", "secp256k1", "rand/std_rng"]
cli = ["clap"]
optimism = ["reth-eth-wire/optimism"]
