[package]
name = "reth-auto-seal-consensus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "A consensus impl for local testing purposes"

[dependencies]
# reth
reth-beacon-consensus.workspace = true
reth-primitives.workspace = true
reth-interfaces.workspace = true
reth-provider.workspace = true
reth-stages.workspace = true
reth-revm.workspace = true
reth-transaction-pool.workspace = true

# async
futures-util.workspace = true
tokio = { workspace = true, features = ["sync", "time"] }
tokio-stream.workspace = true
tracing.workspace = true

[dev-dependencies]
reth-interfaces = { workspace = true, features = ["test-utils"] }
reth.workspace = true
tempfile.workspace = true
clap.workspace = true
jsonrpsee.workspace = true
eyre.workspace = true
serde_json.workspace = true

[features]
# Included solely to ignore certain tests.
optimism = []
