[package]
name = "codecs-derive"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "../README.md"

[package.metadata.cargo-udeps.ignore]
normal = [
  # Used in proc macros
  "serde",
  # Used in proc macros
  "parity-scale-codec",
]

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full", "extra-traits"] }
convert_case = "0.6.0"

# codecs
serde = { workspace = true, default-features = false }
parity-scale-codec = { version = "3.2.1", features = ["derive", "bytes"] }

[dev-dependencies]
pretty_assertions = "1.3.0"

[features]
default = ["compact"]
compact = []
scale = []
postcard = []
no_codec = []
optimism = []
