[package]
name = "reth-payload-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "reth payload builder"

[dependencies]
# reth
reth-primitives.workspace = true
reth-rpc-types.workspace = true
reth-transaction-pool.workspace = true
reth-interfaces.workspace = true
reth-rpc-types-compat.workspace = true

# ethereum
alloy-rlp.workspace = true
revm-primitives.workspace = true

# async
tokio = { workspace = true, features = ["sync"] }
tokio-stream.workspace = true
futures-util.workspace = true

# metrics
reth-metrics.workspace = true
metrics.workspace = true

# misc
thiserror.workspace = true
sha2 = { version = "0.10", default-features = false }
tracing.workspace = true

[dev-dependencies]
revm.workspace = true

[features]
test-utils = []
optimism = [
  "reth-primitives/optimism",
  "reth-rpc-types/optimism",
  "reth-rpc-types-compat/optimism",
  "reth-interfaces/optimism",
  "reth-transaction-pool/optimism"
]
