on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: fuzz
jobs:
  all:
    # Skip the Fuzzing Jobs until we make them run fast and reliably. Currently they will
    # always recompile the codebase for each test and that takes way too long.
    if: false
    runs-on:
      group: Reth
    strategy:
      matrix:
        target:
          - reth-primitives
          - reth-db
          - reth-eth-wire
          - reth-codecs
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install fuzzer
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-test-fuzz cargo-afl

      - name: Run fuzz tests
        run: |
          ./.github/scripts/fuzz.sh ${{ matrix.target }}
        env:
          AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1

  fuzz-success:
    if: always()
    name: fuzz success
    runs-on: ubuntu-latest
    needs: all
    steps:
      # Note: This check is a dummy because we currently have fuzz tests disabled.
      - run: echo OK.
      #- name: Decide whether the needed jobs succeeded or failed
      #  uses: re-actors/alls-green@release/v1
      #  with:
      #    jobs: ${{ toJSON(needs) }}
