# Runs a series of sanity checks for crate consumers.

name: sanity

on:
  workflow_dispatch: {}
  # Once per day at 00:00 UTC
  schedule:
    - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  unused-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        network: ["ethereum", "optimism"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@cargo-udeps
      - name: Check for unused dependencies
        run: cargo udeps --features "jemalloc,${{ matrix.network }}"
      - uses: JasonEtco/create-an-issue@v2
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_URL:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          update_existing: true
          filename: .github/SANITY_UNUSED_DEPS_ISSUE_TEMPLATE.md
