# Runs unit tests.

name: unit

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  SEED: rustethereumethereumrust

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: test / ${{ matrix.network }} (${{ matrix.partition }}/2)
    runs-on:
      group: Reth
    strategy:
      matrix:
        partition: [1, 2]
        network: ["ethereum", "optimism"]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@nextest
      - name: Run tests
        run: |
          cargo nextest run \
            --locked --features "${{ matrix.network }}" \
            --workspace --exclude examples --exclude ef-tests \
            --partition hash:${{ matrix.partition }}/2 \
            -E "kind(lib) | kind(bin) | kind(proc-macro)"

  state:
    name: Ethereum state tests
    runs-on:
      group: Reth
    env:
      RUST_LOG: info,sync=error
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Checkout ethereum/tests
        uses: actions/checkout@v4
        with:
          repository: ethereum/tests
          path: testing/ef-tests/ethereum-tests
          submodules: recursive
          fetch-depth: 1
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - run: cargo nextest run --release -p ef-tests --features ef-tests

  doc:
    name: doc tests (${{ matrix.network }})
    runs-on:
      group: Reth
    timeout-minutes: 30
    strategy:
      matrix:
        network: ["ethereum", "optimism"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Run doctests
        run: cargo test --doc --workspace --features "${{ matrix.network }}"

  unit-success:
    name: unit success
    runs-on: ubuntu-latest
    if: always()
    needs: [test, state, doc]
    timeout-minutes: 30
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
